env:
  commonjs: true
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 12
rules:
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
  object-curly-spacing:
    - error
    - always
    - objectsInObjects: true
  array-bracket-spacing:
    - error
    - never
    - arraysInArrays: false
  space-before-blocks:
    - error
    - functions: always
      keywords: always
      classes: always
  keyword-spacing:
    - error
    - overrides:
        if:
          after: true
        for:
          after: true
        while:
          after: true
        static:
          after: true
        as:
          after: false
  no-undef: warn
  no-undef-init: error
  no-unused-vars: warn
  no-empty: warn
  no-unreachable: 'off'
  no-constant-condition: warn
  no-undefined: warn
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 0
      maxBOF: 0
